### ISSUE TITLE
import errors

### ISSUE THREAD

**Issue by gracca** [aplpy/aplpy#103]
I'm building a graphical interface in **Gtk+ 3** and **Python** in order to create a RGB image using APLpy: the user selects 3 fits files, clicks a button and it creates a png image. 

With the following imports:

``` python
import aplpy
import montage
import subprocess
from gi.repository import Gtk, GdkPixbuf
```

I get this error:

``` python
$ ./makeRGB-frame.py 
Traceback (most recent call last):
  File "./makeRGB-frame.py", line 34, in <module>
    from gi.repository import Gtk, GdkPixbuf
  File "/usr/lib64/python2.7/site-packages/gi/__init__.py", line 27, in <module>
    from ._gi import _API, Repository
ImportError: could not import gobject (error was: ImportError('When using gi.repository you must not import static modules like "gobject". Please change all occurrences of "import gobject" to "from gi.repository import GObject".',))
```

You can see the same question asked here for more details:

http://stackoverflow.com/questions/15557658/import-errors-with-python-and-gtk-3

Any help is appreciated!

**Comment by astrofrog** [comment]
I'm going to close this as this is likely not needed anymore
