### ISSUE TITLE
Montage not showing up when running make_rgb_cube()

### ISSUE THREAD

**Issue by adam-avison** [aplpy/aplpy#111]
I am trying to use make_rgb_cube() in aplpy in the a very simple script (just to confirm things are working or not as is the case).

The script does the following:
<code><br/>import astropy<br/> import aplpy<br/> import montage_wrapper<br/> aplpy.make_rgb_cube(['x_8p0.fits',x_4p5.fits','x_3p6.fits'],'x_cube.fits') </code>

On running this script I get two warnings regarding montage_wrapper, as follows:

<code>WARNING: ConfigurationDefaultMissingWarning: Requested default configuration file /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/montage_wrapper-0.9.5-py2.7.egg/montage_wrapper/montage_wrapper.cfg is not a file. Cannot install default profile. If you are importing from source, this is expected. [pyfits.core]</code>

<code>WARNING: ConfigurationDefaultMissingWarning: Requested default configuration file /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/montage_wrapper-0.9.5-py2.7.egg/montage_wrapper/montage_wrapper.cfg is not a file. Cannot install default profile. If you are importing from source, this is expected.</code>

And the errors from what I assume is aplpy:

<code>ERROR: Exception: Both the Montage command-line tools and the Python-montage module are required for this function [aplpy.rgb]</code>
<code>ERROR: Exception: Both the Montage command-line tools and the Python-montage module are required for this function</code>

With the Traceback referring to the aplpy.make_rgb_cube command.

About Montage, I have the latest version installed and the path to it setup in by .bash_profile. So when I type e.g. mAdd I and output complaining that I didn't use mAdd correctly not that mAdd is unknown (as shown on http://montage-wrapper.readthedocs.org/en/v0.9.5/ ).

About montage_wrapper I currently have the latest version having run downloaded and installed in the past 24hours. In python if I <code>import montage_wrapper as montage</code> and run e.g. <code>montage.mArchiveList('2MASS', 'K', 'm31', 0.5, 0.5, 'm31_list.tbl')</code> this also succeeds. 

I have also clean installed Astropy in the past 24hours and also aplpy (using pip). I'm on a Mac running OS X 10.7.5 and I am using Python 2.7.

Any help much appreciated.

**Comment by astrofrog** [comment]
Apologies for never having replied to this. APLpy now no longer relies on Montage so I'm going to close this.
