### ISSUE TITLE
Add test for FITSFigure.show_regions

### ISSUE THREAD

**Issue by cdeil** [aplpy/aplpy#121]
I ran into the pyregion issue https://github.com/leejjoon/pyregion/issues/20 error while using aplpy.

Add unit test for `FITSFigure.show_regions` to make sure pyregion works well together with astropy / aplpy.

**Comment by astrofrog** [comment]
There is now an image test ``test_regions`` that ensures that the images made with ``show_regions`` are preserved pixel-by-pixel
