### ISSUE TITLE
Plot polarization vectors

### ISSUE THREAD

**Issue by aakepley** [aplpy/aplpy#128]
I know this isn't a common use case, but it would be good to be able to overplot polarization vectors similar to those in the image below.

![screenshot_6_12_13_3_17_pm](https://f.cloud.github.com/assets/2965853/644753/ad1c19ee-d394-11e2-8b26-e652cf8b3ac4.png)

It looks like this could be hacked using lines command, but it would be a nice touch to have it directly in aplpy.

When making this plot, typically you have at least one fits file: one with the polarization angles. If another fits file is included it has the polarized intensity or percent polarization. A couple of useful features would be:
* user-selectable scaling for the length of the polarization vectors,
* a scale bar for the length of the vector (e.g., xxx arcsec is yyy polarized intensity in mJy/beam),
* automatically rotate the vectors (usually by ~90deg to change B vectors to E vectors, but I could think of other cases where the rotation would not be 90), and
* only plot every nth vector.

Let me know if I can do anything to help. I'm a complete Python newbie and a middling procedural programmer. I have a ton of polarization data that could be used to test.

**Comment by revoltek** [comment]
I think this piece of code should be part of Aplpy official release. I've been using an old version of it since quite a while without any problem.

**Comment by keflavich** [comment]
@revoltek - would you be willing to submit the code as a PR so that it can undergo the usual review process?

**Comment by astrofrog** [comment]
@keflavich - I have already opened a PR here: https://github.com/aplpy/aplpy/pull/220 but it had dropped off my radar.

**Comment by astrofrog** [comment]
@mhardcastle @aakepley @revoltek @keflavich - this has now been merged in #220 and will be in APLpy 1.0!

**Comment by mhardcastle** [comment]
Great!

**Comment by aakepley** [comment]
Yay!!!

**Comment by astrofrog** [comment]
APLpy 1.0 is out, so let me know if this doesn't work!

**Comment by mhardcastle** [comment]
Looks like it works fine on code that ran previously under my tree.

**Comment by astrofrog** [comment]
Great, thanks!
