### ISSUE TITLE
show_contours() Error: "Cannot (yet) convert between unknown, none and equatorial, j2000"

### ISSUE THREAD

**Issue by petiay** [aplpy/aplpy#139]
Very nice feature to plot contours.  I am not quite sure how to skip this error and have the code go on, however, because the contours actually are plotted, and they are correct, but the exception terminates the program.  I wonder if there is a way to bypass this exception.  There is really nothing that I need to fix when I look at the plot - it looks fine and the coordinates are correct.

Here is how I am calling the function:

f = aplpy.FITSFigure('imageFile.fits')
g, ghd = pyfits.getdata('imageFile.fits', header=True)
f.show_contour(g, levels=3, colors='k')

I've tried:
f.show_contour(g, hdu=gdh, levels=3, colors='k')

so, explicitly specifying the header to be used by hdu=gdh, but beside being redundant, this doesn't work either.

Thanks again.

**Comment by astrofrog** [comment]
I think this is likely fixed in APLpy 2.0 - please re-open this issue if not!
