### ISSUE TITLE
AVM tagging from AstroPix Beta?

### ISSUE THREAD

**Issue by aakepley** [aplpy/aplpy#148]
Hi,

I'm playing around with trying to overlay some radio contours on a Chandra AstroPix image with AVM information (http://astropix.ipac.caltech.edu/image/383) using the following:

f = aplpy.FITSFigure('vamp---chandra_471_3000.jpg')
f.show_rgb()
f.show_contour('../GBT/M82_if1.mom0.fits')

When I display the image, the RA coordinate system appears to be wrong. The X-ray image appears to be oriented correctly, but the RA axis is backwards (increasing towards the right, instead of increasing towards the left), which causes the contours to be flipped about the vertical axis from their true orientation (stubby arms should be on the left side of image, not right).

![figure_1_and_emacs_starfury3 gb nrao edu](https://f.cloud.github.com/assets/2965853/1390291/24d04fb4-3beb-11e3-98be-4446722a8c62.png)

I don't know if this is a problem in aplpy or the AVM tagging for the Chandra image. If it's a problem with the AVM tagging for the Chandra image, I'll pass this issue on to them.

Please let me know if you could like the contours to test. This data is pre-publication, so I'd rather not put it on the web.

I'm running aplpy 0.9.9 and pyavm 0.9.1.

**Comment by astrofrog** [comment]
@aakepley - sorry for dropping the ball on this issue, I think this should hopefully all be fixed now, 6 years later!...
