### ISSUE TITLE
APLpy not compatible with astropy 0.3

### ISSUE THREAD

**Issue by njcuk9999** [aplpy/aplpy#154]
import aplpy

...site-packages/aplpy/**init**.py in <module>()
--> 125 from .aplpy import FITSFigure
...site-packages/aplpy/aplpy.py in <module>()
---> 60 from . import convolve_util
...site-packages/aplpy/convolve_util.py in <module>()
----> 4 from astropy.nddata import convolve as nddata_convolve, make_kernel

ImportError: cannot import name convolve

Reproduced on another machine and via importing astropy separately:

from astropy.nddata import convolve
<ipython-input-4-14f469a9730d> in <module>()
----> 1 from astropy.nddata import convolve

ImportError: cannot import name convolve

**Comment by indebetouw** [comment]
This bug has reappeared for me. I just did a fresh install of anaconda, and then added pyregion, pyAVL, Pillow, montage-wrapper all using conda. 
In [4]: astropy.__version__
Out[4]: u'1.2.1'

In [5]: !conda list aplpy
# packages in environment at /Users/kej7a/anaconda:
#
Using Anaconda Cloud api site https://api.anaconda.org
aplpy                     1.0                      py27_0    astropy

In [6]: import aplpy
/Users/kej7a/anaconda/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-429eb0b27113> in <module>()
----> 1 import aplpy

/Users/kej7a/.local/lib/python2.7/site-packages/aplpy/__init__.py in <module>()
    123     del os, warn, config_dir  # clean up namespace
    124
--> 125 from .aplpy import FITSFigure
    126 from .rgb import make_rgb_image, make_rgb_cube
    127

/Users/kej7a/.local/lib/python2.7/site-packages/aplpy/aplpy.py in <module>()
     58
     59 from . import contour_util
---> 60 from . import convolve_util
     61 from . import image_util
     62 from . import header as header_util

/Users/kej7a/.local/lib/python2.7/site-packages/aplpy/convolve_util.py in <module>()
      2
      3 import numpy as np
----> 4 from astropy.nddata import convolve as nddata_convolve, make_kernel
      5
      6

ImportError: cannot import name convolve

Any suggestions as to what I've done wrong?  Thanks.
