### ISSUE TITLE
How do we create contour plot with aplpy ?

### ISSUE THREAD

**Issue by neuronphysics** [aplpy/aplpy#166]
In the documentation of aplpy there is not enough explanation to elaborate how we can create contour plot? It seems it should be generated first via matplotlib contour plot then use for e.g. matplotlib._cntr to first make a list of contours with trace() which in the case that I would like to logarithmically plot my data it won't work. Then apply something like pyfits to make a contour fits file. Again I have no idea how I can convert a list of arrays to a contour fits file. Finally use show_contour('contour.fits') to overlay the contours on the astronomical image. Can you post an example of how it works?? Thanks in advance.

**Comment by astrofrog** [comment]
For anyone looking at this issue - if you have a FITS image and want to show contours, you just need to do:

```
fig.show_contours('image_file.fits')
```

i.e. there is no need to pre-compute any contours in advance.
