### ISSUE TITLE
mystery standard wcs types

### ISSUE THREAD

**Issue by snarkysarah** [aplpy/aplpy#236]
I'm attempting to plot a position (x-axis) velocity (y-axis) diagram using a fits image. Integrating over one of the position axes of a cube, I have already created the PV fits file (NAXIS=2) and updated the header to reflect the units / CDELT values (pv-int.fits in the below example) with 
CTYPE1  = 'GLON-SIN'  
CTYPE2  = 'VELO-LSR'

When I try to import it into aplpy, it complains about wcs type.
> from astropy.io import fits
> im=fits.open('pv-int.fits')
> fig=aplpy.FITSFigure(im[0])

InconsistentAxisTypesError: ERROR 4 in wcs_types() at line 2136 of file cextern/wcslib/C/wcs.c:
Unmatched celestial axes.

I can't find what are accepted wcs types. Is there another way of reading in the fits file that aplpy would find more agreeable?

**Comment by keflavich** [comment]
@snarkysarah - a quick workaround is to change "GLON-SIN" to "OFFSET".  WCSLIB, which aplpy uses via astropy.wcs, requires that any celestial axis (ra, dec, glon, glat) be in a matched pair with the appropriate partner.

@astrofrog - I have run into this issue a lot too.  I thought I had raised it at some point but I can't find it.  Perhaps we should implement a workaround where unmatch celestial axes get automatically renamed to 'OFFSET' internally, but then label the axis with the ctype from the header?

**Comment by astrofrog** [comment]
@keflavich - yes, maybe we should indeed detect this and work around the ``astropy.wcs`` limitations.

**Comment by snarkysarah** [comment]
@keflavich Work-around worked. Thank you.
For posterity's sake, 

> im[0].header['CTYPE1'] = 'OFFSET'

Cheers.
