### ISSUE TITLE
make_rgb_cube has bad reprojection for HST images?

### ISSUE THREAD

**Issue by keflavich** [aplpy/aplpy#253]
@astrofrog - this is almost certainly a montage issue.  

I've tried assembling RGB images from archive.stsci.edu/prepds/wfc3ers/m83datalist.html and found that ds9 aligns them fine, but aplpy's `make_rgb_cube` results in misaligned star (clusters).  I haven't investigated further but I want the report up.

**Comment by astrofrog** [comment]
I need to check, but we may ignore distortions because there wasn't an ``all_world2pix`` before. But we could fix that now.

**Comment by keflavich** [comment]
True, we can switch to `all_world2pix` in `wcs_util.py` very easily, but I've verified that the problem is in the reprojection step for this particular case.

**Comment by keflavich** [comment]
@astrofrog on closer inspection, I was wrong - the images are intrinsically misaligned.
