### ISSUE TITLE
problem with the tutorial: labels.py and Unicode

### ISSUE THREAD

**Issue by stellarpuffin** [aplpy/aplpy#262]
I am new in using python and I've already encountered an error in the APLpy tutorial.

I have Python 2.7.10 and all the latest versions of numpy, scipy, matplotlib, astropy, aplpy etc., via MacPorts (Mac OSX 10.8.5)

Now, I started the tutorial given on the APLpy website and encountered the following error right after loading the 2MASS file:

```python
bash-3.2$ ipython --pylab
Python 2.7.10 (default, May 25 2015, 13:16:30) 
Type "copyright", "credits" or "license" for more information.
IPython 3.1.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.
Using matplotlib backend: MacOSX
In [1]: import astropy
In [2]: import aplpy
In [3]: gc = aplpy.FITSFigure('fits/2MASS_k.fits')
/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/aplpy/labels.py:432: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if self.coord == x or self.axis.apl_tick_positions_world[ipos] > 0:
In [4]:
```

A figure box is loaded with what I presume must have been the 2MASS map, but the window is blank except for the coordinates' frame.

Any idea about what's missing?

I haven't tested anything else, since I encountered this problem.

**Comment by astrofrog** [comment]
@stellarpuffin - I *think* this may not be a severe issue but I will investigate. Try typing ``gc.show_colorscale`` to see if the image appears.

**Comment by stellarpuffin** [comment]
@astrofrog Thanks! I tried to continue the exercise as you suggested and everything works fine. But I still get the same warning every time I load a FITS file (my own or one from your tutorials).
