### ISSUE TITLE
Sphinx build broken

### ISSUE THREAD

**Issue by cdeil** [aplpy/aplpy#263]
Looks like the aplpy Sphinx build is broken:
https://travis-ci.org/aplpy/aplpy/jobs/64336052#L800

It also doesn't work with Python 2 and 3 (different errors) for me locally with `master`:
https://gist.github.com/cdeil/217307da00b8a301a8e3

**Comment by astrofrog** [comment]
Ah yes, I think I need to update to the latest astropy-helpers to fix this.

**Comment by cdeil** [comment]
Still broken: https://travis-ci.org/aplpy/aplpy/jobs/76849092#L829

**Comment by bsipocz** [comment]
This seems to be solved, or at least the sphinx builds are passing atm.
