### ISSUE TITLE
Using APLPy in interactive mode with the standard python shell?

### ISSUE THREAD

**Issue by smaret** [aplpy/aplpy#274]
Is there a way to use APLPy in an interactive fashion without using `ipython --pylab`? I've tried to run the tutorial with the standard `python` shell ( Python 2.7.10, APLPy 0.9.14, MacOSX 10.11.1), but the figure does not appear on the screen. I've tried both the `MacOSX` and `GTK3Agg` backends.

**Comment by astrofrog** [comment]
Try doing:

```
import matplotlib.pyplot as plt
plt.show()
```

after setting up FITSFigure.

**Comment by smaret** [comment]
It works, thanks!

I wonder if there would be a way for APLPy to detect if it is imported from the standard `python` shell  and to call `matplotlib.pyplot.show()` automatically if needed?
