### ISSUE TITLE
WCS is not celestial Issue

### ISSUE THREAD

**Issue by pandasarebest** [aplpy/aplpy#283]
Hi there, so for my masters project im using APLpy to look at fits files. Initially this didnt come with the celestial information, however I have added that using the documentation on pyfits/astropy.

I then try to run the code to show the image, and then to 'show circles' in this case, and it is consistently throwing up the error 'WCS is not celestial, cannot determine celestial pixel scale'

The code I'm running is:

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import Image
import pyfits
import os
import aplpy
from astropy.io import fits

dir = '/home/simon/PROJECT/Github/Test'
os.chdir(dir)

hdulist = fits.open('lc_0001c.fits', mode = 'update')
hdu = fits.PrimaryHDU()
print hdu.header

hdu.header['NAXIS'] = (2, 'Changed from 0, for array dimensions')
hdu.header['NAXIS1'] = (512)
hdu.header['NAXIS2'] = (640)
hdu.header['CTYPE1'] = ('RA---TAN', 'Using Galactic Longitude')
hdu.header['CTYPE2'] = ('DEC---TAN', 'Using Galactic Latitude')
hdu.header['CRVAL1'] = (100, 'Value on Postion CRPIX1')
hdu.header['CRVAL2'] = (100, 'Value on Postion CRPIX2')
hdu.header['CRPIX1'] = (256, 'Pixel Position of CRVAL1')
hdu.header['CRPIX2'] = (320, 'Pixel Position of CRVAL2')
hdu.header['CDELT1'] = (-0.000112233, 'Pixel scale of CRPIX1 in Degrees') #THIS NEEDS UPDATING ONCE EXCEL IS DONE
hdu.header['CDELT2'] = (0.00112233, 'Pixel scale of CRPIX2 in Degrees') #THIS NEEDS UPDATING ONCE EXCEL IS DONE
hdu.header['EQUINOX'] = (2000.0)
hdu.header['MAGZP'] = (50)
hdu.header['BSCALE'] = (0.045777)
hdu.header['BZERO'] = (1500)

print hdu.header
hdulist.close()

hdulist = pyfits.open('lc_0001c.fits')
print hdu.header
hdulist.close()

fig =  aplpy.FITSFigure('lc_0001c.fits')
fig.add_grid()
fig.grid.show()
fig.show_grayscale()
fig.set_auto_refresh(True)

fig.show_circles(256,320, 10)

and then the console runs through everything. shows the image in greyscale as required, and then throws up the error. I have tried it with other fits files, and they usually work just fine.

Is there something really obvious that im not mentioning in the code????

Any help would be much appreciated.

Simon

**Comment by keflavich** [comment]
FITS keywords are 8 characters.  Should be DEC--TAN (remove one -)

**Comment by pandasarebest** [comment]
Hi Kefla, thanks for noticing that particular error.
It still however doesn't remove the WCS error that I am getting.

**Comment by astrofrog** [comment]
@pandasarebest - sorry for the delay! If editing the file in 'update' mode isn't working, please report the issue to the Astropy [issue tracker](https://github.com/astropy/astropy/issues). Note that you can also just do ``hdulist.writeto('newfile.fits')`` before closing it or simply pass the HDU object to ``FITSFigure`` to get around the issue. I'm going to close this a the issue seems unrelated to APLpy itself.
