### ISSUE TITLE
recenter() leads to core dump on all-sky images

### ISSUE THREAD

**Issue by hsuyeep** [aplpy/aplpy#285]
I'm trying to display a subset of pixels from my all-sky field of view image. A mwe for ipython follows:

```
import aplpy;
import matplotlib.pyplot as plt;
fig1 = plt.figure();
aimg1 = aplpy.FITSFigure ('sb003_10sec_012315_trunc.fits', figure=fig1);
aimg1.pixel2world (512, 512)
(87.881072097800001, 52.915122434540002)

In [28]: aimg1.recenter (87.88, 52.91, radius=20)
*** Error in `/usr/bin/python': free(): invalid next size (fast): 0x0000000003d9f0a0 ***
Aborted (core dumped)
```

Note that the image has pixels where the WCS is invalid, due to those pixels being below the horizon, and this also prevents the coordinate grid from being displayed.
[sb003_10sec_012315_trunc.fits.gz](https://github.com/aplpy/aplpy/files/105144/sb003_10sec_012315_trunc.fits.gz)

**Comment by astrofrog** [comment]
It looks like this should be fixed in APLpy 2.0 - let me know if not!
