### ISSUE TITLE
Change the default cmap from jet to anything else

### ISSUE THREAD

**Issue by bsipocz** [aplpy/aplpy#293]
Maybe it's time to change the default jet [0] to something else e.g. viridis [1]? 

[0] - https://github.com/aplpy/aplpy/blob/8db94c108aaac3fbeb026dcb512053aed2c43cac/aplpy/core.py#L920
[1] - https://twitter.com/astrofrog/status/623088520740118533

**Comment by astrofrog** [comment]
Yes please! :) Or alternatively ``plasma`` (one of the other new colormaps) - I have the impression the green colormap is not to everyone's taste

**Comment by bsipocz** [comment]
Should it fall back to jet, or something else for <1.5?

**Comment by astrofrog** [comment]
The default is now viridis, and we only support Matplotlib 2.0 and above
