### ISSUE TITLE
matplotlib 1.5 issue

### ISSUE THREAD

**Issue by cas0010** [aplpy/aplpy#294]
Hello, I've been using APLpy to find and plot sources in my .fits images, but have been getting this warning when I display my .fits files. Could someone explain the issue to me and help  resolve this issue?

In [3]: comet.show_colorscale(cmap='Blues_r')
INFO: Auto-setting vmin to  8.541e+02 [aplpy.core]
INFO: Auto-setting vmax to  3.316e+03 [aplpy.core]
This has been deprecated in mpl 1.5, please use the
axes property.  A removal date has not been set.
This has been deprecated in mpl 1.5, please use the
axes property.  A removal date has not been set.

**Comment by jslavin** [comment]
The deprecation warning seems to be related to the use of the get_axes() method of the axis object.  That method is used in ticks.py in the WCSLocator class __call__ method.  It could be fixed, I think by replacing
        ymin, ymax = self.axis.get_axes().yaxis.get_view_interval()
        xmin, xmax = self.axis.get_axes().xaxis.get_view_interval()
with
        ymin, ymax = self.axis.axes.yaxis.get_view_interval()
        xmin, xmax = self.axis.axes.xaxis.get_view_interval()

**Comment by evertrol** [comment]
@cas0010 Note that it's just a warning. Everything will work fine as is. Only in the (far) future, if you'd upgrade matplotlib to a (yet non-existent) matplotlib version, this would become an actual error.

If the warning annoys you, you can wrap the offending lines with `warnings.catch_warnings():`
```python
        import warnings
        import matplotlib as mpl
        with warnings.catch_warnings():
            warnings.filterwarnings(
                "ignore", category=mpl.cbook.MatplotlibDeprecationWarning)
```

**Comment by jslavin** [comment]
True, for now.  But in the future it could become an error.  I suppose I could submit a pull request.  The fix is certainly easy enough.

**Comment by jslavin** [comment]
I see that you've submitted a pull request to fix this.  Thanks!
