### ISSUE TITLE
Quick Reference Has Wrong Unit Name for Jy/beam

### ISSUE THREAD

**Issue by nbrunett** [aplpy/aplpy#296]
Hopefully this is the right place to submit things we notice about the documentation. In the Quick Reference Guide for 2.0 dev857 there is an example of changing the colorbar label which reads

`f.colorbar.set_axis_label_text('Flux (Jy/beam)')`

but Jy/beam is not a flux. Those units should be called something like "Spectral Brightness", "Specific Intensity", "Intensity" or "Surface Brightness". See [here](https://www.cv.nrao.edu/course/astr534/Interferometers2.html), fourth paragraph after equation 3G3 which starts "The intensity axis of any astronomical image..." or the the Synthesis Imaging in Radio Astronomy White Book p127 (Taylor, Carilli & Perley). I would change the above code snippet to

`f.colorbar.set_axis_label_text('Surface Brightness (Jy/beam)')`

**Comment by astrofrog** [comment]
@nbrunett - indeed, this should be fixed :) Could you open a pull request? If you are not familiar with git, you can simply go to:

https://github.com/aplpy/aplpy/blob/master/docs/quick_reference.rst

and click the 'edit' icon in the top right.

**Comment by nbrunett** [comment]
I'm not trying to nudge anyone along, I'm just curious about if I did things correctly here since the pull request has been sitting a while now. If people simply have bigger fish to fry I totally understand. Thanks.

**Comment by astrofrog** [comment]
@nbrunett - sorry for the delay, I've been traveling a lot. The fix looks good so I went ahead and merged it - thanks!
