### ISSUE TITLE
Remove (deprecate) pyfits import?

### ISSUE THREAD

**Issue by evertrol** [aplpy/aplpy#308]
I got bitten recently by a confusing issue with a pyfits import, which happened because aplpy was imported.
Should the pyfits compatibility be removed from aplpy v2.x?
I don't know what exception will be raised for users still relying on pyfits, but would that exception be obvious enough to point out that pyfits is not supported anymore by aplpy?

Perhaps something similar applies to `pyWCS` as well?
The combination would force users to switch and update scripts to  astropy completely, but that's already an aplpy requirement.

**Comment by astrofrog** [comment]
I think it would be fine to now remove support for PyFITS and PyWCS, as people really should update to Astropy now. I'll fix this.

**Comment by astrofrog** [comment]
Done in 40905c91405441f2324c48f0e0a65079749499b9
