### ISSUE TITLE
Get 'cannot determine equinox' warning even when equinox defined in header

### ISSUE THREAD

**Issue by Stargrazer82301** [aplpy/aplpy#309]
Every time I put any FITS file through `aplpy.FITSFigure`, I get the warning:

`WARNING: Cannot determine equinox. Assuming J2000. [aplpy.wcs_util]`

Even though I have an `EQUINOX` entry in my headers, set to 2000.0. And a `RADESYS` entry, and an `EPOCH` entry.

As this means I get tens of thousands of copies of this warning flashing over my console, making it impossible to read any other output, I tried disabling all console output by means of `sys.stdout = open(os.devnul, "w")`, the warnings still appears!

**Comment by astrofrog** [comment]
@Stargrazer82301 - could you share a file that causes this issue? You can upload it somewhere and give me the URL, or send it to thomas.robitaille@gmail.com

**Comment by Stargrazer82301** [comment]
Here's a example file that causes the issue:

https://www.dropbox.com/s/1s8mv46hfc5dv95/JINGLE72_Spitzer_70.fits.gz?dl=0

[JINGLE72_Spitzer_70.fits.zip](https://github.com/aplpy/aplpy/files/485262/JINGLE72_Spitzer_70.fits.zip)

(Also, I found that the warning messages can be disabled with the astropy logging system, at leas!)

**Comment by astrofrog** [comment]
It looks like this should be fixed in APLpy 2.0 - let me know if not!
