### ISSUE TITLE
Issues with tick labels in aplpy

### ISSUE THREAD

**Issue by rayadastidar** [aplpy/aplpy#313]
Hi all, 
I have written a simple code using APLpy to mark some stars in a fits image. 

**import aplpy
import matplotlib.pyplot as plt
import numpy as np
ra,dec = np.loadtxt('data.txt', unpack=True, usecols=(1,2))
gc = aplpy.FITSFigure('new-image.fits', north=True)
gc.set_theme('publication')
gc.show_grayscale(vmin=100, vmax=600, invert=True,stretch='linear')
gc.show_circles(ra, dec, radius=0.005,edgecolor='white')
gc.show_lines([np.array([[185.4898333,185.4898333],[4.4739722,4.4819722]])],color='white')
gc.show_lines([np.array([[185.4914167,185.4982917],[4.4716111,4.4716111]])],color='white')
x,y = np.loadtxt('data.txt', unpack=True, usecols=(3,4))
text = np.loadtxt('label.txt', unpack=True, dtype=np.dtype('a1'))
for i in range(len(x)):
    gc.add_label(x[i], y[i], text[i],color='white')

def format_for_allsky(gc):
    gc.tick_labels.set_xformat('hr:mm:ss')
    gc.tick_labels.set_yformat('dd:mm:ss')
    gc.ticks.set_xspacing(0.03325)
    gc.ticks.set_yspacing(0.050)
    gc.tick_labels.set_font(size='small')
    gc.axis_labels.set_xtext('Right Ascension (J2000)')
    gc.axis_labels.set_ytext('Declination (J2000)')
    gc.tick_labels.set_style('colons')
format_for_allsky(gc)
plt.show()
gc.save('test.pdf',dpi=600)**

Everything works fine but the x (RA) tick labels show only ss or mm:ss and not the whole value hh:mm:ss. Could you please help me in getting around this problem?

**Comment by bmarcote** [comment]
Change
gc.tick_labels.set_xformat('hr:mm:ss')
to
gc.tick_labels.set_xformat('hh:mm:ss')

Instead of "hh:mm:ss" you had "hr"mm"ss".

An error or at least a warning should be shown in these cases. Although it is not.
