### ISSUE TITLE
Files README.rst and LICENSE.rst missing from pypi tarball

### ISSUE THREAD

**Issue by sergiopasra** [aplpy/aplpy#316]
README.rst and LICENSE.rst are in the github repo but are missing from pypi tarball (1.1)

**Comment by astrofrog** [comment]
Oops, good catch, will try and get a fix out ASAP

**Comment by astrofrog** [comment]
Fixed in 888311647a13cb059c51d45edf78d95bd3e0f34c

**Comment by astrofrog** [comment]
I've now released 1.1.1 which fixes this - can you confirm?
