### ISSUE TITLE
x,y limits in aplpy

### ISSUE THREAD

**Issue by rayadastidar** [aplpy/aplpy#320]
How to plot only a range of RA/DEC using aplpy.FITSFigure? Like in matplotlib we can use 
 **plt.axis([xmin,xmax,ymin,ymax])**  to define the limits.

**Comment by saimn** [comment]
I guess you are looking for the [recenter](http://aplpy.readthedocs.io/en/stable/api/aplpy.FITSFigure.html#aplpy.FITSFigure.recenter) method ?

**Comment by rayadastidar** [comment]
Yes, that's right! Thanks!
