### ISSUE TITLE
FITSFigure.show_markers not placing markers at the right position

### ISSUE THREAD

**Issue by astrochun** [aplpy/aplpy#329]
I'm am doing a simple overlay of circles for a set of stars with ra/dec. However, the outputted PDF does not place the circles on top of the stars.  Instead, it is off by a noticeable amount.  I checked the WCS for the provided FITS image and the coordinates in ds9, and the coordinates are dead center.

Here's just a snippet of how I call show_markers
gc.show_markers(mag_table['ra_2mass'], mag_table['dec_2mass'],
                    edgecolor='red', facecolor='none', marker='o',
                    s=15, linewidth=0.5)

Any idea why this might be a problem. For reference, the input FITS image has a RA-TAN/DEC-TAN projection with no rotation. Pretty simple.

**Comment by astrofrog** [comment]
@astrochun - could you send the image and catalog you are using to thomas.robitaille@gmail.com?

**Comment by astrochun** [comment]
I found this outstanding issue that was resolved privately with Tom. I'm closing this issue.
