### ISSUE TITLE
Can't run tests locally because of --mpl option

### ISSUE THREAD

**Issue by keflavich** [aplpy/aplpy#331]
If I try to run `python setup.py test`, I get the following error:

```
usage: -c [options] [file_or_dir] [file_or_dir] [...]
-c: error: unrecognized arguments: --mpl
  inifile: /private/var/folders/_r/c4nkvmpn4vx6qc91qygz8h740000gr/T/aplpy-test-fvnv2_11/setup.cfg
  rootdir: /private/var/folders/_r/c4nkvmpn4vx6qc91qygz8h740000gr/T/aplpy-test-fvnv2_11
```

Am I missing some dependency?

**Comment by astrofrog** [comment]
Yes, you need to install pytest-mpl (with pip)

**Comment by keflavich** [comment]
Thanks, that did indeed solve it.

When I run the tests, mpl windows are continuously popping up and disappearing, preventing me from accessing any other window on my system.  Do you have any idea why that's happening?  I would have expected the calls of `matplotlib.use('agg')` to prevent that.
