### ISSUE TITLE
figure not showing

### ISSUE THREAD

**Issue by astropatel** [aplpy/aplpy#336]
I am having an issue now that I can't plot fits files that I used to be able to. I don't know if it's because of an update that I made. I have attached the fits file and the code I'm using here (remove the .txt extension before testing). Any help would be appreciated.

matplotlib : 2.0.0
aplpy: 1.1.1

import aplpy
fileS = 'HIP100001_unWISE_1_w3.fits'
ax1 = aplpy.FITSFigure(filesS)

The only thing I get is the following:

![image](https://cloud.githubusercontent.com/assets/3648312/24326833/ff45c680-1174-11e7-9250-ae894653f752.png)

[HIP100001_unWISE_1_w3.fits.txt](https://github.com/aplpy/aplpy/files/870433/HIP100001_unWISE_1_w3.fits.txt)

**Comment by umitkavak** [comment]
Hi astropel,

As I seen, you just open your fits file without show anything in map. If you put following line you obtain map I attached. 

import aplpy

file = "test.fits"
ax1  = aplpy.FITSFigure(file)
ax1.show_colorscale(cmap="viridis", vmin=40, vmax=500)
ax1.save('test.png', dpi = 400)

![test](https://cloud.githubusercontent.com/assets/26542534/24365292/c30625e6-1315-11e7-9071-49620d9be840.png)

**Comment by umitkavak** [comment]
Btw, you can change vmin and vmax value to obtain meaningful map. For example, I changed vmin = 400 and vmax = 8000. Then I have produced below map. 

![test](https://cloud.githubusercontent.com/assets/26542534/24365513/7a1e8cb4-1316-11e7-8a86-85a4fad54a34.png)

**Comment by astropatel** [comment]
Ah. Thank you. In the past, I never had to play around with the scaling to have it visually display the image. This helps quite a bit!
