### ISSUE TITLE
RECENTER   free(): invalid pointer

### ISSUE THREAD

**Issue by daisyzepeda** [aplpy/aplpy#337]
>>> import matplotlib.pyplot as plt
>>> import numpy as np
>>> import aplpy
>>> f = aplpy.FITSFigure('AzTEC_Orion_FRUIT_SHIMAJIRI.fits')
>>> f.recenter(83.819298, -5.0020772, width=0.07, height=0.07)
*** Error in `python': free(): invalid pointer: 0x0000000003208960 ***
Abortado
CAN YOU PLEACE HELP ME ?

**Comment by astrofrog** [comment]
@daisyzepeda - could you share the FITS file you are using with me? I will keep it private. You can send it to thomas.robitaille@gmail.com. Thanks!

**Comment by astrofrog** [comment]
I'm going to close this as I think it was likely an issue with a specific build of astropy or matplotlib, and shouldn't be an issue anymore.
