### ISSUE TITLE
 Use a lot of memory when I save FITS file to image

### ISSUE THREAD

**Issue by kyeongyeon** [aplpy/aplpy#339]
My FITS image is hundred megabyte or few gigabyte.
When I save the FITS file to image as 'png', code was canceled with 'segmentation fault' message. 
I think ....it is cause of memory problem. Server that I use has 6.0 Gb free memory cause many people use it together.
So, ....Is there any way to reduce memory usage as I save to image?

**Comment by astrofrog** [comment]
@kyeongyeon - do you have the same issue you if you make a simple plot with the same data in Matplotlib? e.g.

```python
from astropy.io import fits
import matplotlib.pyplot as plt
hdu = fits.open('largefile.fits')
ax = plt.subplot(1,1,1)
ax.imshow(hdu.data)
fig.savefig('test.png')
```
