### ISSUE TITLE
Vanishing photons in X-ray image (interpolation problem in imshow?) 

### ISSUE THREAD

**Issue by sczesla** [aplpy/aplpy#343]
Hi,

First, thanks for providing your great package.

I use aplpy to plot X-ray images, which are characterized by a lot of empty pixels and only some with a few photon counts. Curiously, I noticed that some photons definitely present in the image (e.g., using ds9) were not displayed. Even more curiously, the exact picture depends on seemingly unrelated settings like font size.

Hunting down the issue, I think I identified the problem in the show_colorscale routine. If I use "none" for the interpolation parameter in imshow instead of "nearest", the image will be correctly displayed (at least I think so). Also removing the extent option has this effect, but it shifts the image. I assume this may be a numerical issue with the half-pixel coordinate system introduced by extent. Depending on the exact binary representation of the pixel coordinate one or the other neighbor is selected to be the "nearest" one, which results in strange artifacts in cases such as X-ray images.

Below, I provide a minimal example to demonstrate the issue.

```
import aplpy
import numpy as np

im = np.zeros( (101,101) )
im[::2,::2] = 1.0

gc = aplpy.FITSFigure(im)
gc.show_grayscale(invert=True)
gc.save('chess.eps')  
```

I am not sure whether using 'none' as interpolation option would generally be a workable solution for the package. 

Cheers,
Stefan

**Comment by keflavich** [comment]
The difference between 'none' and 'nearest' is backend-dependent (see http://matplotlib.org/api/pyplot_api.html#matplotlib.pyplot.imshow).  I wasn't aware that there was any difference between these options and I don't know what the difference would be; can you reproduce this issue at all with a generated data set using `matplotlib.pyplot.imshow`?

**Comment by sczesla** [comment]
Good point. No I cannot reproduce this using imshow directly. Backend is "TkAgg".

In fact, well-formed pngs are produced independent of interpolation. I can produce correctly looking eps and pdfs by increasing dpi in "save" (default is 13) by  factor of a few.  So maybe the problem originates there. Can you reproduce the behavior or is it particular to my machines (Ubuntu 16.04 and 12.04)?

**Comment by keflavich** [comment]
I don't have the appropriate data to reproduce the issue, but dpi is very likely to be the issue.  dpi=13 is really really coarse; dpi=150 might be better for publication-quality figures and dpi=75 for on-screen.  aplpy autoselects a dpi that is sometimes appropriate, but not always...

**Comment by sczesla** [comment]
All right. The code snippet above should do the trick; no data required. At any rate, I hope I will have some time to look at this a little further because the effect may well have gone unnoticed, which can be a little evil.

**Comment by keflavich** [comment]
My bad, I didn't read carefully enough.

Yes, I can reproduce the issue.  If I save as png, I get:
![test](https://cloud.githubusercontent.com/assets/143715/26083456/378dc510-3993-11e7-9eca-4391e664120b.png)

As PDF, weird things happen:
[test.pdf](https://github.com/aplpy/aplpy/files/1002734/test.pdf)

but if I turn up the dpi, we're back to a good image:
[test_150.pdf](https://github.com/aplpy/aplpy/files/1002738/test_150.pdf)

**Comment by sczesla** [comment]
Yep. that is about how it looks for me, too; should have attached the figures right away. Maybe a lower limit for dpi would prevent such things. Not sure whether it would a sufficiently general solution, however...
