### ISSUE TITLE
update of python libraries: tick direction suddenly 'out'

### ISSUE THREAD

**Issue by MagdalenaBrunner** [aplpy/aplpy#345]
I recently updated my python libraries (anaconda, aplpy and some minor others) and after that update I noticed that aplpy will now plot tick marks with direction 'out' instead of 'in'.

I suspect that this is because of changed default parameter settings in matplotlib 2.0 (I noticed the same issue on a simple non-aplpy plot).

**EDIT:**

The workaround, as described in the matplotlib changelog, is to include
```
mpl.rcParams['xtick.direction'] = 'in'
mpl.rcParams['ytick.direction'] = 'in'
```
to reset to the old default tick direction.

**Comment by astrofrog** [comment]
Indeed, this is just a change in the Matplotlib defaults - thanks for posting the workaround!
