### ISSUE TITLE
aplpy plots a strange axis 

### ISSUE THREAD

**Issue by philastrophist** [aplpy/aplpy#358]
For some reason, aplpy sometimes plots an axis with a non-uniform scale. I can't figure out why. DS9 plots them as they are supposed to look but aplpy doesn't

The fits files are attached at the bottom

code:
```
import aplpy 
from astropy.io import fits
aplpy.FITSFigure(fits.open(fname)[0])
```

versions: 
astropy==2.01
aplpy==1.1.1
py3.6.1

Good:
![good_coordinates](https://user-images.githubusercontent.com/14169057/29929529-a4d4b9c4-8e63-11e7-9632-328c1cc9d7f3.png)

Bad:
![bad_coordinates](https://user-images.githubusercontent.com/14169057/29929532-a6a0630c-8e63-11e7-83d2-879b5101aba6.png)

[good coordinate fits file](https://drive.google.com/file/d/0B3DW_geiS1_TV2w0c2lRS2ZmVVE/view?usp=sharing)
[bad coordinate fits file](https://drive.google.com/file/d/0B3DW_geiS1_TSEVoVkhrZERIbFE/view?usp=sharing)

**Comment by astrofrog** [comment]
So the  issue here is that the coordinate axes are rotated at close to 90 degrees relative to the pixel axes, which caused issues with APLpy's previous way of finding ticks and tick labels.

I'd recommend using APLpy 2.0 and specifying ``north=True`` when you create ``FITSFigure``, this will ensure that the Declination axis is lined up with the pixel y values.
