### ISSUE TITLE
An update to a link

### ISSUE THREAD

**Issue by ysBach** [aplpy/aplpy#363]
In the explanation of [log scale](http://aplpy.readthedocs.io/en/stable/normalize.html#log-scale), a link is broken:
> where $a$ defaults to 1000 and recommended values are from 100-10000 (see [here](http://ds9.si.edu/ref/how.html)).

The correct link to this "here" should be: http://ds9.si.edu/doc/ref/how.html

**Comment by astrofrog** [comment]
This section has since been removed, so closing this.
