### ISSUE TITLE
Default axis label format changed

### ISSUE THREAD

**Issue by ysBach** [aplpy/aplpy#366]
The default axis formats seem to have changed recently. For example, the [Beginner Tutorial](http://aplpy.readthedocs.io/en/stable/quickstart.html) of APLPy will have the {°, ', "} formatted RA/DEC axes:
![myfirstplot](https://user-images.githubusercontent.com/17214293/31254898-80bf0760-aa65-11e7-970a-39ee1d0ac21c.png)

The original document shows " 11d 22m 33s " format for DEC and " 11h 22m 33s " format for RA.

I currently could not find any way to recover the "hms" format:
* `gc.tick_labels.set_style('plain')` doesn't do anything.
* `gc.tick_labels.set_xformat('hh:mm:ss')` shows the RA inappropriately: hms format but in "degrees" symbols.

Is there a way to show RA values in conventional " 11h 22m 33s " format?

**Comment by hsdalgleish** [comment]
Yes! I am having the same problem. It was working fine before, and now it doesn't (possibly because I upgraded to Python 3?)
Have you managed to resolve it?

**Comment by astrofrog** [comment]
This has now been fixed in APLpy 2.0 - try upgrading and let me know if the default is not in the HMS format!
