### ISSUE TITLE
mpl_toolkits.axes_grid module was deprecated

### ISSUE THREAD

**Issue by astrosuri** [aplpy/aplpy#370]
Hi, 

I am having trouble reading fits files with aplpy.FITSFigure(), because the matplotlib axes_grid module is no longer there after version 2.1. 

I get the following error:
AttributeError: 'XAxis' object has no attribute 'get_axes'

Best,
Sümeyye Suri

**Comment by ggurkan** [comment]
Is there any solution to this issue, I am having the same.

**Comment by astrofrog** [comment]
@astrosuri @ggurkan - this should now be fixed in APLpy 2.0 - try upgrading and feel free to re-open if you are still running into this!
