### ISSUE TITLE
Direction tick marks

### ISSUE THREAD

**Issue by NikkiZabel** [aplpy/aplpy#371]
Hi, the option to change the direction of the tick marks seems to have been removed in the latest version. Why is that? I'd really like to be able to have them on the inside of my figure! Thanks!

**Comment by rainsworth** [comment]
Hello! Is this still an open issue? All of the documentation shows images with tick marks inside the plot, but no matter what I do, they only plot outside of my aplpy.FITSFigure plots.

**Comment by Sunmish** [comment]
As far as I know this hasn't been fixed, however [astrofrog has suggested using this at the beginning of your script](https://github.com/astropy/astropy/issues/6735) as a workaround:

```python
import matplotlib as mpl
mpl.rcParams['xtick.direction'] = 'in'
mpl.rcParams['ytick.direction'] = 'in'
```

This workaround has worked nicely for me.

**Comment by astrofrog** [comment]
You can now do this with ``fig.ticks.set_tick_direction('in')`` (or ``'out'``)
