### ISSUE TITLE
data cube at different channels 

### ISSUE THREAD

**Issue by nkandpal** [aplpy/aplpy#377]
I have a data cube for a xyz molecule which gives me values at a particular channel value . However on aplpy the final image does not give me complete image .
Is there any way in aplpy that i can change the channel values to get a much better  fits image .

**Comment by nkandpal** [comment]
Got it . it was the slices parameter in the FITSFigure option. One of the values for different channels.

**Comment by astrofrog** [comment]
Yes, that's the best way to do it :) Sorry for not replying sooner!
