### ISSUE TITLE
New release to help with CI

### ISSUE THREAD

**Issue by bsipocz** [aplpy/aplpy#388]
A few packages rely on aplpy for their CI (e.g. astroquery). The last release, 1.1.1 had a requirement of python<3.5.2, thus the python 3.5 CI builds are still running on that rather old 3.5.1 version.

It would be rather useful to have a new build available that doesn't have this requirement any more. I'm happy to help out either if you decide to have a new release, or if we just ship a new conda package (the configparser issue that was the reason for the version limitation had already been fixed in 1.1.1 so probably it's enough just to have a new build)

**Comment by astrofrog** [comment]
APLpy 2.0 is out! 🎉
