### ISSUE TITLE
Image shrinking after showing the fits file

### ISSUE THREAD

**Issue by botteon** [aplpy/aplpy#390]
Hi,

I've just installed APLpy on a new laptop with the software up to date:
APLpy v1.1.1
Matplotlib v 2.2.2

After that I show the FITS file with `show_grayscale` or `show_colorscale`, every command that I give makes the image shrink. This happens only in interactive mode (`ipython --matplotlib`), when I run the same script (`python script.py`) the output is fine.

I thought it was related to these issues (https://github.com/matplotlib/matplotlib/issues/8736?_pjax=%23js-repo-pjax-container and https://github.com/matplotlib/matplotlib/issues/8717) but I have the latest software versions....any idea?
Thank you.

**Comment by botteon** [comment]
This is a matplotlib related issue, see https://github.com/matplotlib/matplotlib/issues/9913
I tried TKAgg and Qt4Agg backends, but both show the same problem. 
I have installed Matplotlib v2.2.2 with` pip`

**Comment by botteon** [comment]
The problem doesn't occur with Matplotlib v 2.1.2

**Comment by astrofrog** [comment]
I'm going to close issue since it is a Matplotlib bug and there is an issue open in their repository (matplotlib/matplotlib#9913)
