### ISSUE TITLE
Changing colorbar tick labels

### ISSUE THREAD

**Issue by jrcallingham** [aplpy/aplpy#400]
I am using v1.1.1 and trying to change the colour bar tick labels. I can position the ticks using colorbar.set_ticks but I can not manually adjust the colour bar label (in this case I just want to multiply the values by 1000). Suggest this would be useful feature.

Sorry if it is already possible and missed it!

Joe

**Comment by astrofrog** [comment]
I agree this would be useful - there is already an issue open (#389) so I'll close this one.
