### ISSUE TITLE
Deprecation warning, treated as error, with numpy 1.16

### ISSUE THREAD

**Issue by olebole** [aplpy/aplpy#406]
With the latest numpy (which is now in Debian), I get the following deprecation warnings, which seem to be treated as errors (full log [here](https://ci.debian.net/data/autopkgtest/testing/amd64/a/aplpy/1592220/log.gz)):
```
        # 2018-10-10, 1.16
        warnings.warn('np.asscalar(a) is deprecated since NumPy v1.16, use '
>                     'a.item() instead', DeprecationWarning, stacklevel=1)
E       DeprecationWarning: np.asscalar(a) is deprecated since NumPy v1.16, use a.item() instead
```
I guess, just being less pedantic here would help for the moment, right?
Slightly related: I am going to upload astropy 3.1 soon (also with a fix for the new numpy), and it seems that aplpy would need some update (#405); however since #392 and #394 are now closed without comment, I am curious whether a new version wll happen soon? On the other hand, #405 is quite big to backport to 1.1.1. Do you have any advise here?

**Comment by astrofrog** [comment]
@olebole - I am going to release 2.0 imminently

**Comment by astrofrog** [comment]
@olebole - can you try out the 2.0rc1 release?

**Comment by olebole** [comment]
A test build for 2.0rc1 works well. Thanks for the quick reaction!
