### ISSUE TITLE
APLpy downsample

### ISSUE THREAD

**Issue by cosmicshear** [aplpy/aplpy#414]
The downsampling feature in APLpy 2.0rc2 does not seem to work for me. Can anyone reproduce the following?

```python
import numpy as np
import aplpy
import matplotlib.pyplot as plt

data = np.arange(256).reshape((16, 16))
f = aplpy.FITSFigure(data, downsample=2)
f.show_grayscale()
plt.show()
```

![downsample aplpy](https://user-images.githubusercontent.com/2823824/52705893-ddf4e900-2f38-11e9-8816-98c3a08c172a.png)

**Comment by astrofrog** [comment]
I’ll investigate, thanks for the report! Always good to know people are trying out the release candidates - very helpful!

**Comment by astrofrog** [comment]
@cosmicshear - this was a real bug and is fixed in the latest developer version.

**Comment by cosmicshear** [comment]
@astrofrog - thanks!
