### ISSUE TITLE
Installing the develop version?

### ISSUE THREAD

**Issue by mconsidine** [aplpy/aplpy#499]
Hi,
I'd like to install the latest bleeding edge version, but running
  python setup.py aplpy
fails, as setup.py doesn't exist in the github archive.
Can someone point out what I am missing?  Apologies in advance if I have missed something otherwise obvious.
Regards,
mconsidine

**Comment by jdgsmallwood** [comment]
Hi, have you tried 
```
cd aplpy
pip install .
```
(or pip3 on some flavours of linux)
from a terminal within the folder?

The package uses a pyproject.toml which is a successor to a setup.py and pip knows how to read this.

You can also install the package in editable mode (changes you make to the code are automatically loaded) using 
```
pip install -e .
```

**Comment by astrofrog** [comment]
Using ``pip install .`` is indeed correct (or with the ``-e``).

Just FYI I have just released APLpy v2.2.0 which is now up-to-date with the latest developer version.
