### ISSUE TITLE
aplpy incompatible with 3.12?

### ISSUE THREAD

**Issue by profxj** [aplpy/aplpy#508]
I'm finding `aplpy 2.1` is failing on import when used with 
  python 3.12 and `astropy 6.1.4`

I haven't tried this is in a fresh conda environment, but mine isn't too loaded.
Here is the trace:

(astro_312) wolverine> python
Python 3.12.5 | packaged by Anaconda, Inc. | (main, Sep 12 2024, 18:27:27) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import aplpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xavier/anaconda3/envs/astro_312/lib/python3.12/site-packages/aplpy/__init__.py", line 9, in <module>
    from ._astropy_init import *  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xavier/anaconda3/envs/astro_312/lib/python3.12/site-packages/aplpy/_astropy_init.py", line 21, in <module>
    from astropy.config.configuration import (
ImportError: cannot import name 'update_default_config' from 'astropy.config.configuration' (/home/xavier/anaconda3/envs/astro_312/lib/python3.12/site-packages/astropy/config/configuration.py)
>>> import astropy
>>> print(astropy.__version__)
6.1.4
>>> 
(astro_312) wolverine> pip show aplp
WARNING: Package(s) not found: aplp
(astro_312) wolverine> pip show aplpy
Name: aplpy
Version: 2.1.0
Summary: The Astronomical Plotting Library in Python
Home-page: http://aplpy.github.io
Author: Thomas Robitaille and Eli Bressert
Author-email: thomas.robitaille@gmail.com
License: MIT
Location: /home/xavier/anaconda3/envs/astro_312/lib/python3.12/site-packages
Requires: astropy, matplotlib, numpy, pillow, pyavm, pyregion, reproject, scikit-image, shapely

**Comment by r-xue** [comment]
Just came across the same issue. 

It might not be tied to the in-use Python version, rather than some Astropy changes and the API uses in the dated aplpy version released on PyPI (the last release there was from 2022).

Meanwhile, the MAIN branch directly from this repo seems to work fine: pip install git+https://github.com/aplpy/aplpy.git

**Comment by astrofrog** [comment]
I have just released APLpy 2.2.0 - could you confirm that this works fine?

**Comment by r-xue** [comment]
> I have just released APLpy 2.2.0 - could you confirm that this works fine?

Yes. That works. Thanks for the fast response!
