### ISSUE TITLE
Provide an option to align rgb images north

### ISSUE THREAD

**Issue by astrofrog** [aplpy/aplpy#6]
Originally submitted by Médéric Boquien:

Hello,

I think it would be nice to have an option to align rgb images north. For now, if i pass north=True to FITSFigure(), it rotates the coordinates grid only and not the image. As a workaround, i have hardcoded the -n option to os.system('mMakeHdr images_raw.tbl header.hdr') in make_rgb_cube().

Thanks,

Médéric

**Comment by keflavich** [comment]
@astrofrog - is this solved? https://github.com/aplpy/aplpy/blob/master/aplpy/rgb.py#L234

**Comment by astrofrog** [comment]
This is indeed solved, as ``north=True`` can now be passed to ``make_rgb_cube``
